# application-stg.yaml
server:
  port: 8080
spring:
  application:
    name: user-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    show-sql: ${SPRING_JPA_SHOW_SQL}
    properties:
      hibernate:
        format_sql: ${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL}
  security:
    enabled: ${SPRING_SECURITY_ENABLED}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
security:
  ignored: ${SECURITY_IGNORED}
  basic:
    enabled: ${SECURITY_BASIC_ENABLED}
  user:
    name: ${SECURITY_USER_NAME}
    password: ${SECURITY_USER_PASSWORD}

