server:
  port: 8082
spring:
  application:
    name: user-service
# profiles set with kustomize overlays, and for local development in IDE configuration
# profiles:
    #active: local, kafka-enabled
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: user-service-group
    topic: my-topic
management:
  endpoints:
    web:
      exposure:
        #include: "*" # Expose all Actuator endpoints (if using Actuator)
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
  security:
    enabled: false # Disable Actuator security
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
logging:
  level:
    root: INFO
    com.store: DEBUG
#  level:
#    org:
#      apache:
#        kafka: DEBUG
security:
  ignored: ${SECURITY_IGNORED}
  basic:
    enabled: ${SECURITY_BASIC_ENABLED}
  user:
    name: ${SECURITY_USER_NAME}
    password: ${SECURITY_USER_PASSWORD}
  jwt:
    secret-key: ${SECURITY_JWT_SECRET_KEY}

