apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  template:
    spec:
      containers:
        - name: user-service
          envFrom:
            - configMapRef:
                name: user-service-config
            - secretRef:
                name: user-service-secret
