apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 8082 # The port on the service
      targetPort: 8080 # The port on the pod (minikube worked)
  type: ClusterIP

