apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  template:
    spec:
      containers:
        - name: user-service
          resources:
            requests:
              cpu: 80m
              memory: 192Mi
            limits:
              cpu: 250m
              memory: 384Mi

